using System;
using System.Collections.Generic;

namespace Natukaship
{
    public class Features
    {
        public bool push { get; set; }
        public bool iCloud { get; set; }
        public bool inAppPurchase { get; set; }
        public bool gameCenter { get; set; }
        public bool LPLF93JG7M { get; set; }
        public bool passbook { get; set; }
        public bool IAD53UNK2F { get; set; }
        public bool V66P55NK2I { get; set; }
        public string dataProtection { get; set; }
        public bool SKC3T5S89Y { get; set; }
        public bool APG3427HIY { get; set; }
        public bool HK421J6T7P { get; set; }
        public bool homeKit { get; set; }
        public bool WC421J6T7P { get; set; }
        public int cloudKitVersion { get; set; }
    }

    public class Capability
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public bool enabledByDefault { get; set; }
        public string imageUrl { get; set; }
        public List<object> entitlementList { get; set; }
    }

    public class AppId
    {
        /// <summary>
        /// The identifier of this app, provided by the Dev Portal
        /// </summary>
        /// @example
        ///   "RGAWZGXSAA"å
        public string appIdId { get; set; }

        /// <summary>
        /// The name you provided for this app
        /// </summary>
        /// @example
        ///   "Natukaship"
        public string name { get; set; }

        /// <summary>
        /// The supported platform of this app
        /// </summary>
        /// @example
        ///   "ios"
        public string appIdPlatform { get; set; }

        /// <summary>
        /// Prefix provided by the Dev Portal
        /// </summary>
        /// @example
        ///   "5A997XSHK2"
        public string prefix { get; set; }

        /// <summary>
        /// The bundle_id (app identifier) of your app
        /// </summary>
        /// @example
        ///   "com.krausefx.app"
        public string identifier { get; set; }

        /// <summary>
        /// Is this app a wildcard app (e.g. com.krausefx.*)
        /// </summary>
        public bool isWildCard { get; set; }

        /// <summary>
        /// Feature details
        /// </summary>
        public Features features { get; set; }

        /// <summary>
        /// List of enabled services
        /// </summary>
        public List<string> enabledFeatures { get; set; }

        /// <summary>
        /// Development Push Enabled?
        /// </summary>
        public bool? isDevPushEnabled { get; set; }

        /// <summary>
        /// Production Push Enabled?
        /// </summary>
        public bool? isProdPushEnabled { get; set; }

        /// <summary>
        /// Number of associated app groups
        /// </summary>
        public object associatedApplicationGroupsCount { get; set; }

        /// <summary>
        /// Number of associated cloud containers
        /// </summary>
        public object associatedCloudContainersCount { get; set; }

        /// <summary>
        /// Number of associated identifiers
        /// </summary>
        public object associatedIdentifiersCount { get; set; }

        /// <summary>
        /// Associated groups
        /// </summary>
        public object associatedApplicationGroups { get; set; }

        /// <summary>
        /// Associated cloud containers
        /// </summary>
        public object associatedCloudContainers { get; set; }

        /// <summary>
        /// Associated identifiers
        /// </summary>
        public object associatedIdentifiers { get; set; }

        public bool isDuplicate { get; set; }
        public object canEdit { get; set; }
        public object canDelete { get; set; }
        public List<Capability> capabilities { get; set; }
    }

    public class ProvisioningProfile
    {
        /// <summary>
        /// The ID generated by the Dev Portal
        /// You'll probably not really need this value
        /// </summary>
        /// @example
        ///   "2MAY7NPHAA"
        public string provisioningProfileId { get; set; }

        /// <summary>
        /// The name of this profile
        /// </summary>
        /// @example
        ///   "com.krausefx.app AppStore"
        public string name { get; set; }

        /// <summary>
        /// The status of this profile
        /// </summary>
        /// @example Active (profile is fine)
        ///   "Active"
        /// @example Expired (time ran out)
        ///   "Expired"
        /// @example Invalid (e.g. code signing identity not available any more)
        ///   "Invalid"
        public string status { get; set; }

        /// <summary>
        /// The type of the profile (development or distribution).
        /// You'll probably not need this value
        /// </summary>
        /// @example Distribution
        ///   "iOS Distribution"
        /// @example Development
        ///   "iOS Development"
        public string type { get; set; }

        /// <summary>
        /// The profile distribution type. You probably want to
        /// use the class type to detect the profile type instead of this string.
        /// </summary>
        /// @example AppStore Profile
        ///   "store"
        /// @example AdHoc Profile
        ///   "adhoc"
        /// @example Development Profile
        ///   "limited"
        /// @example Mac Developer ID Profile
        ///   "direct"
        public string distributionMethod { get; set; }
        public string distributionType { get; set; }

        /// <summary>
        /// The supported platform for this profile
        /// </summary>
        /// @example
        ///   "ios"
        public string proProPlatform { get; set; }

        /// <summary>
        /// This will always be "2"
        /// </summary>
        /// @example
        ///   "2"
        public string version { get; set; }

        /// <summary>
        /// The date and time of when the profile expires
        /// in readable text
        /// </summary>
        /// @example
        ///   "2020-11-14T10:06:22Z"
        public string dateExpireString { get; set; }

        /// <summary>
        /// The date and time of when the profile expires
        /// </summary>
        /// @example
        ///   "Nov 14, 2020"
        public DateTime dateExpire { get; set; }

        /// <summary>
        /// The App ID this profile is for
        /// </summary>
        public AppId appId { get; set; }

        /// <summary>
        /// The ID of App ID this profile is for
        /// </summary>
        public string appIdId { get; set; }

        /// <summary>
        /// A list of devices this profile is enabled for
        /// </summary>
        public List<Device> devices { get; set; }

        /// <summary>
        /// A list of device ids this profile is enabled for
        /// </summary>
        public List<string> deviceIds { get; set; }

        /// <summary>
        /// A list of certificates used for this profile
        /// </summary>
        public List<Certificate> certificates { get; set; }

        /// <summary>
        /// A list of certificate ids used for this profile
        /// </summary>
        public List<string> certificateIds { get; set; }

        /// <summary>
        /// Does the profile use a template (has extended entitlements)?
        /// </summary>
        /// @example
        ///   false
        public bool isTemplateProfile { get; set; }

        /// <summary>
        /// The UDID of this provisioning profile
        /// This value is used for example for code signing
        /// It is also contained in the actual profile
        /// </summary>
        /// @example
        ///   "23d7df3b-9767-4e85-a1ea-1df4d8f32fec"
        public string UUID { get; set; }

        public bool isTeamProfile { get; set; }
        public bool isFreeProvisioningProfile { get; set; }
        public string requesterNickName { get; set; }
        public string requesterFirstName { get; set; }
        public string requesterLastName { get; set; }
        public string requesterEmail { get; set; }
    }

    public class GetProvisioningProfileResponseObject
    {
        public DateTime creationTimestamp { get; set; }
        public int resultCode { get; set; }
        public string userLocale { get; set; }
        public string protocolVersion { get; set; }
        public string requestUrl { get; set; }
        public string responseId { get; set; }
        public bool isAdmin { get; set; }
        public bool isMember { get; set; }
        public bool isAgent { get; set; }
        public ProvisioningProfile provisioningProfile { get; set; }
    }
}
